version: "3.7"
services:
  dns:
    image: qmcgaw/dns
    container_name: dns
    environment:
      - VERBOSITY=1
      - VERBOSITY_DETAILS=0
      - BLOCK_MALICIOUS=on
      - BLOCK_SURVEILLANCE=on
      - BLOCK_ADS=off
      - BLOCK_IPS=
      - BLOCK_HOSTNAMES=
      - UNBLOCK=
      - PROVIDERS=cloudflare,quad9
      - UPDATE_PERIOD=24h
    ports:
      - 53:53/udp
    network_mode: bridge
    restart: always
